Completed Redux-Store
graceshoppers/grace-shoppers pull request #36
Opened 2019-04-28 14:04 UTC by Marfuen

not very DRY... Just want to get it working. Can refactor later to look prettier.

2019-04-28 15:46 UTC, trufflebao requested changes
Hey @Marfuen can we use presents tense for updateproduct instead of updated product, just want to keep it consistent with create product.
Also if u take a look in the server/api routes, thats where the axios are supposed to go. Like axios.get(‘/api/product’)
Once the axios routes r changed to /api/ then i think we can merge and test. You can actually merge dev down now and test it to make sure ur store works

2019-04-28 19:14 UTC, kevinydhan reviewed
Hi Mariano,
Most of it looks good. I think some minor changes and it should be good to merge!

2019-04-28 19:14 UTC, ydhan18 commented on src/redux-store/store.js
> +const updatedCategory = (category, id) => {
I don't think you need to have the `id` as a parameter since the API route is returning the entire `Category` object.

2019-04-28 19:14 UTC, ydhan18 commented on src/redux-store/store.js
> +const updatedProduct = (product, id) => {
Same here

2019-04-28 19:14 UTC, ydhan18 commented on src/redux-store/store.js
> +const updatedUser = (user, id) => {
"

2019-04-28 19:14 UTC, ydhan18 commented on src/redux-store/store.js
> +const reducer = (state = initialState, action) => {
We'll need to break this reducer up later on :(

2019-04-29 15:43 UTC, Marfuen reviewed
Fixed issues that you guys brought up

2019-04-29 15:43 UTC, Marfuen commented on src/redux-store/store.js
> +const updatedCategory = (category, id) => {
I see what you're saying. Makes sense.

2019-04-29 23:46 UTC, trufflebao requested changes
sorry the api routes changed to plural so /api/products, /api/categories, and /api/users. Once that is change we should be good. @Marfuen

2019-04-30 01:01 UTC, trufflebao approved these changes

2019-04-30 01:02 UTC, merged